# Generated by Django 3.2.19 on 2023-05-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
                ('birth_year', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('lack_health', models.CharField(choices=[('Rarm', '오른팔 팔꿈치 위'), ('Larm', '왼팔 팔꿈치 위'), ('Relbow', '오른팔 팔꿈치 아래'), ('Lelbow', '왼팔 팔꿈치 아래'), ('Rwaist', '오른쪽 허리'), ('Lwaist', '왼쪽 허리'), ('Rleg', '오른쪽 허벅지'), ('Lleg', '왼쪽 허벅지'), ('Rknee', '오른쪽 종아리'), ('Lknee', '왼쪽 종아리')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_data')),
            ],
        ),
    ]
