# Generated by Django 3.2.19 on 2023-05-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='lack_health',
            field=models.CharField(choices=[('arm', '왼팔 팔꿈치'), ('elbow', '팔꿈치 아래'), ('waist', '허리'), ('leg', '허벅지'), ('knee', '종아리')], max_length=10),
        ),
    ]
